### ISSUE TITLE
npm包还是6.1.4，求同步

### ISSUE THREAD

**Issue by Guozihong** [whtiehack/pinus-global-channel-status#207]
![image](https://user-images.githubusercontent.com/21210394/114811321-84222f00-9de0-11eb-99be-97ab83d793d6.png)

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/115556982-d46b2680-a2e3-11eb-8381-66baa7d1506c.png)
包发布不了..token也换 了..好奇怪

**Comment by Guozihong** [comment]
我直接访问:https://registry.npmjs.org/pinus-global-channel-status
这个网址是有东西的，那个报错404就有点奇怪了
发布的账号切成这个包的账号没有，我之前直接发就出去了，没遇到这个问题

**Comment by whtiehack** [comment]
手动发布了.. action 不知道为啥发布不了
